import turtle
fe=turtle.Turtle(shape="turtle")
fe.pensize(10)
fe.circle(50)
fe.color("blue")
fe.pensize(10)
fe.penup()
fe.setposition(-120, 0)
fe.pendown()
fe.circle(50)
fe.color("green")
fe.pensize(10)
fe.penup()
fe.setposition(60, 60)
fe.pendown()
fe.circle(50)
fe.color("yellow")
fe.pensize(10)
fe.penup()
fe.setposition(-60, 60)
fe.pendown()
fe.circle(50)
fe.color("red")
fe.pensize(10)

fe.penup()
fe.setposition(-180, 60)
fe.pendown()
fe.circle(50)
fe.color("black")
fe.pensize(10)

turtle.done()